apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.k8s.sebatec.eu
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: k8s.sebatec.eu
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
  scope: Namespaced
  names:
    plural: databases
    singular: database
    kind: Database
    shortNames:
    - db
