{{- if (or .Values.secret.create .Release.IsInstall) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: {{ include "mariadb.secretPassword" (list . .Values.secret.rootPassword) }}
  MARIADB_OPERATOR_SEED: {{ include "mariadb.secretPassword" (list . .Values.secret.operatorSeed) }}
{{- end }}
